mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', include('root.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^pollsSV/', include('pollsSV.urls', namespace="pollsSV")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/pollsSV/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/root/urls.py
from django.conf.urls import patterns, url

from root import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

mysite/polls/models.py
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

mysite/pollsSV/models.py
from django.db import models

# Create your models here.

mysite/root/models.py
from django.db import models

# Create your models here.

mysite/polls/views.py
# Create your views here.
from polls.models import Poll, Choice
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

#def index(request):
#    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]   
#    context = {'latest_poll_list': latest_poll_list}
#    return render(request, 'polls/index.html', context) 

def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'poll': p,
            'error_message': "You din't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/pollsSV/views.py
# Create your views here.
from polls.models import Poll, Choice
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'pollsSV/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'poll': p,
            'error_message': "You din't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/root/views.py
# Create your views here.
from polls.models import Poll, Choice
from django.shortcuts import render

def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]   
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'root/index.html', context) 

mysite/polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
	{% csrf_token %}
	{% for choice in poll.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

mysite/pollsSV/templates/pollsSV/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pollsSV:vote' poll.id %}" method="post">
	{% csrf_token %}
	{% for choice in poll.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>

mysite/pollsSV/templates/pollsSV/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pollsSV:detail' poll.id %}">Vote again?</a>

mysite/root/templates/root/index.html
{% if latest_poll_list %}
<ul>
{% for poll in latest_poll_list %}
	<li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
	<li><a href="{% url 'pollsSV:detail' poll.id %}">{{ poll.question }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}